name: dub-publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  publish:
    uses: dlang-supplemental/dub-publish/.github/workflows/register-package.yml@main
    with:
      package: kdl
      url: https://github.com/${{ github.repository }}
      root: .
      ignore_fork: true
    secrets:
      DUB_REGISTRY_USER: ${{ secrets.DUB_REGISTRY_USER }}
      DUB_REGISTRY_PASSWORD: ${{ secrets.DUB_REGISTRY_PASSWORD }}
